name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c7938c262fa68a3efc98d914ef48d1c3c9ea0952f2529d30c7f44bb3d2b6086"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
