name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "321b4183757d1fbbe721d59ee0b6a06122f9254dd7e2417a8b5083005d64c4c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
