name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09e02ddf9e1ac4ee6c32762516e908d31504a0dffdc84a3cfbaef1642cb522ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
